version: "3.3"

services:
  sisyphus-client:
    restart: always
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      HOSTNAME_OVERRIDE: ${HOSTNAME}
      API_URL: ${API_URL}
    volumes:
      - /mnt/phoenix:/mnt/phoenix
